# Generated by Django 5.1.7 on 2025-04-02 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_category_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
