# Generated by Django 5.1.7 on 2025-04-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
    ]
